// This file is auto-generated by scripts/generate-elements-host.js
// Do not edit manually. Update components.json in each sub-project instead.

export interface ComponentMetadata {
  tag: string;
  component: string;
  project: string;
  description: string;
}

export interface ComponentsRegistry {
  lastUpdated: string;
  totalComponents: number;
  components: ComponentMetadata[];
}

/**
 * Complete registry of all available web components
 * Updated automatically when npm run generate:elements is executed
 */
export const COMPONENTS_REGISTRY: ComponentsRegistry = {
  "lastUpdated": "2026-06-07T16:27:30.704Z",
  "totalComponents": 2,
  "components": [
    {
      "tag": "ui-card",
      "component": "UiCard",
      "project": "ui-card",
      "description": "Flexible container component for displaying content"
    },
    {
      "tag": "ui-table",
      "component": "UiTable",
      "project": "ui-table",
      "description": "Data table component for displaying structured information"
    }
  ]
};

/**
 * Helper to get component by tag name
 */
export function getComponent(tag: string): ComponentMetadata | undefined {
  return COMPONENTS_REGISTRY.components.find((c) => c.tag === tag);
}

/**
 * Get all components for a specific project
 */
export function getProjectComponents(project: string): ComponentMetadata[] {
  return COMPONENTS_REGISTRY.components.filter((c) => c.project === project);
}
