import { createApplication } from '@angular/platform-browser';
import { createCustomElement } from '@angular/elements';
import { UiCard } from 'ui-card';
import { UiTable } from 'ui-table';

// This file is auto-generated by scripts/generate-elements-host.js
// Do not edit manually. Instead, update components.json in each sub-project.

// Bootstrap a headless Angular application, then register every component
// as a standards-based Custom Element so they can be used in any framework
// or in plain HTML via <script src="elements-host.js">.
(async () => {
  const app = await createApplication();

  const UiTableElement = createCustomElement(UiTable, { injector: app.injector });
  customElements.define('ui-table', UiTableElement);

  const UiCardElement = createCustomElement(UiCard, { injector: app.injector });
  customElements.define('ui-card', UiCardElement);
})();
